added yml file password/username

diff --git a/.github/workflows/api-tests.yml b/.github/workflows/api-tests.yml
--- a/.github/workflows/api-tests.yml
+++ b/.github/workflows/api-tests.yml
@@ -12,6 +12,8 @@ jobs:
 
     env:
       BASE_URL: ${{ secrets.BASE_URL }}
+      USERNAME: ${{ secrets.BOOKER_USERNAME }}
+      PASSWORD: ${{ secrets.BOOKER_PASSWORD }}
 
     steps:
       - name: Checkout repository
@@ -20,16 +22,23 @@ jobs:
       - name: Set up JDK 25
         uses: actions/setup-java@v4
         with:
-          java-version: '25'
           distribution: 'temurin'
+          java-version: '25'
           cache: maven
 
+      - name: Verify required environment variables
+        run: |
+          if [ -z "$BASE_URL" ] || [ -z "$USERNAME" ] || [ -z "$PASSWORD" ]; then
+            echo "Required GitHub secrets are missing!"
+            exit 1
+          fi
+
       - name: Build and run API tests
-        run: mvn clean test
+        run: mvn clean test -Dbase.url=$BASE_URL -Dusername=$USERNAME -Dpassword=$PASSWORD
 
       - name: Upload Surefire Report
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: surefire-report
+          name: surefire-reports
           path: target/surefire-reports
